name: The Contentious Politics Of AI
remote_theme:  mmistakes/minimal-mistakes
plugins:
- jekyll-remote-theme
title: The Contentious Politics Of AI
description: We are a network of academics, policy researchers, and activists interested in ways that AI is contested.

nav:
  - title: Home
    url: /
  - title: News
    url: /news/
    side: left
    dropdown:
    - title: "News"
      url: "/news/"

  # - title: anypage   
  #   url: /anypage/    # a .md file named anypage.md must exist in the root directory
